### ISSUE TITLE
the code living?

### ISSUE THREAD

**Issue by xiaowasly** [Esri/quickstart-map-ios#3]
I want to learn the ArcGIS for iOS , but Official website is not have OC code. Therefore I find you ,the demo is not  update?  I at present use the OC Main exploitation ,Can you answer me? Thank you!

**Comment by nixta** [comment]
Hi @xiaowasly, I might not entirely understand your question, but I think this might help:

1) The ArcGIS Runtime SDK for iOS is very much alive at https://developers.arcgis.com/ios/ and you can find guides to using it [here](https://developers.arcgis.com/ios/latest/swift/guide/introduction.htm), with accompanying samples [here](https://developers.arcgis.com/ios/latest/swift/sample-code/sample-code.htm).
2) The current Runtime SDK indeed supports Objective-C. In fact, it's written in Objective-C.
3) While the samples are in Swift, the [Guide](https://developers.arcgis.com/ios/latest/objective-c/guide/display-a-map.htm) section is available in Swift and Objective-C (see the toggle at the top of each Guide page).
2) This repo is rather old and hasn't been maintained. It targets the old Runtime SDK. If you're keen to learn the new SDK but the Guide and Samples don't help, feel free to reach out on our [forums at GeoNet](https://geonet.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-ios/content).

Perhaps this also helps address https://github.com/Esri/arcgis-runtime-samples-ios/issues/254

**Comment by xiaowasly** [comment]
First , thank you for your answer.  In fact , I found same samples  [here](https://github.com/Esri/arcgis-runtime-samples-ios/tree/master/arcgis-ios-sdk-samples) , it's written in Swift .Because of my project is old , it's written in Objective-C. So ,# **I want to learn the demo written in   Objective-C**,but I can't find .
# 
At present,The ArcGIS Runtime SDK for iOS updated version trend Swift ? 

My English is poor ,Thank you for your patience.

**Comment by nixta** [comment]
Sorry to report that there is not sample code for the new Runtime in Objective-C.

But if you stick to the [Guide](https://developers.arcgis.com/ios/latest/objective-c/guide/display-a-map.htm) and select **Objective-C** at the top, or browse the [API Reference](https://developers.arcgis.com/ios/latest/api-reference/interface_a_g_s_geo_view.html#ae646345b91684f3a1d9ca206fd2b1ae3), you will see that is all Objective-C.

Apple's focus is very much on Swift, so our samples will be in Swift.

However, we will support Objective-C developers for some time yet (it is not yet practical for us to develop the SDK in Swift (e.g. we would require ABI stability since we ship compiled libraries, and Swift hasn't got there yet)).

The patterns, class names and method names don't change though. It should be mostly fairly simple, if a little time-consuming, to translate Swift sample code to Objective-C. I would suggest you find the samples you're interested in and you will still learn good information. You will have to translate it to Objective-C though. And if you get stuck, please feel free to reach out at the [GeoNet iOS Forum](https://geonet.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-ios/content).

Sorry I don't have a better answer for you!

**Comment by xiaowasly** [comment]
Thank you again for your patience ,It's very valuable to me.
It seems that I still want to learn more about ArcGIS.
I understand what you mean ,your answer is good enough.
Thanks a lot.
